<?php

namespace XLite\Model\Proxy\__CG__\XLite\Model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Module extends \XLite\Model\Module implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * {@inheritDoc}
     * @param string $name
     */
    public function __get($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

        return parent::__get($name);
    }

    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', array($name, $value));

        return parent::__set($name, $value);
    }

    /**
     * {@inheritDoc}
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', array($name));

        return parent::__isset($name);

    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'moduleID', 'name', 'author', 'authorEmail', 'enabled', 'installed', 'yamlLoaded', 'date', 'rating', 'votes', 'downloads', 'price', 'currency', 'majorVersion', 'minorVersion', 'build', 'minorRequiredCoreVersion', 'revisionDate', 'packSize', 'xcnPlan', 'moduleName', 'authorName', 'description', 'iconURL', 'pageURL', 'authorPageURL', 'dependencies', 'tags', 'fromMarketplace', 'isLanding', 'landingPosition', 'marketplaceID', 'isSystem', 'hasLicense', 'editionState', 'editions', 'xbProductId', 'imageURLCached', 'isSkin', 'private', 'wave', 'salesChannelPos', 'purchaseStatus', '_previous_state');
        }

        return array('__isInitialized__', 'moduleID', 'name', 'author', 'authorEmail', 'enabled', 'installed', 'yamlLoaded', 'date', 'rating', 'votes', 'downloads', 'price', 'currency', 'majorVersion', 'minorVersion', 'build', 'minorRequiredCoreVersion', 'revisionDate', 'packSize', 'xcnPlan', 'moduleName', 'authorName', 'description', 'iconURL', 'pageURL', 'authorPageURL', 'dependencies', 'tags', 'fromMarketplace', 'isLanding', 'landingPosition', 'marketplaceID', 'isSystem', 'hasLicense', 'editionState', 'editions', 'xbProductId', 'imageURLCached', 'isSkin', 'private', 'wave', 'salesChannelPos', 'purchaseStatus', '_previous_state');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Module $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getMainClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMainClass', array());

        return parent::getMainClass();
    }

    /**
     * {@inheritDoc}
     */
    public function callModuleMethod($method, $result = NULL, array $args = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'callModuleMethod', array($method, $result, $args));

        return parent::callModuleMethod($method, $result, $args);
    }

    /**
     * {@inheritDoc}
     */
    public function checkModuleMainClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'checkModuleMainClass', array());

        return parent::checkModuleMainClass();
    }

    /**
     * {@inheritDoc}
     */
    public function getActualName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActualName', array());

        return parent::getActualName();
    }

    /**
     * {@inheritDoc}
     */
    public function getVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersion', array());

        return parent::getVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function getFullMinorVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullMinorVersion', array());

        return parent::getFullMinorVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function hasIcon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasIcon', array());

        return parent::hasIcon();
    }

    /**
     * {@inheritDoc}
     */
    public function getPublicIconURL()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublicIconURL', array());

        return parent::getPublicIconURL();
    }

    /**
     * {@inheritDoc}
     */
    public function getPublicImageURL($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublicImageURL', array($image));

        return parent::getPublicImageURL($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getSettingsForm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSettingsForm', array());

        return parent::getSettingsForm();
    }

    /**
     * {@inheritDoc}
     */
    public function getDependencyModules($onlyDisabled = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDependencyModules', array($onlyDisabled));

        return parent::getDependencyModules($onlyDisabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getDependentModules()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDependentModules', array());

        return parent::getDependentModules();
    }

    /**
     * {@inheritDoc}
     */
    public function canDisable($safeCheck = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'canDisable', array($safeCheck));

        return parent::canDisable($safeCheck);
    }

    /**
     * {@inheritDoc}
     */
    public function isHardEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isHardEnabled', array());

        return parent::isHardEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function hasEnabledDependentModules()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasEnabledDependentModules', array());

        return parent::hasEnabledDependentModules();
    }

    /**
     * {@inheritDoc}
     */
    public function canUninstall()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'canUninstall', array());

        return parent::canUninstall();
    }

    /**
     * {@inheritDoc}
     */
    public function canEnable($safeCheck = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'canEnable', array($safeCheck));

        return parent::canEnable($safeCheck);
    }

    /**
     * {@inheritDoc}
     */
    public function isModuleCompatible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isModuleCompatible', array());

        return parent::isModuleCompatible();
    }

    /**
     * {@inheritDoc}
     */
    public function hasWrongDependencies($safeCheck = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasWrongDependencies', array($safeCheck));

        return parent::hasWrongDependencies($safeCheck);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabledMutualModules()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabledMutualModules', array());

        return parent::getEnabledMutualModules();
    }

    /**
     * {@inheritDoc}
     */
    public function isFree()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFree', array());

        return parent::isFree();
    }

    /**
     * {@inheritDoc}
     */
    public function isPurchased()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPurchased', array());

        return parent::isPurchased();
    }

    /**
     * {@inheritDoc}
     */
    public function isAvailable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAvailable', array());

        return parent::isAvailable();
    }

    /**
     * {@inheritDoc}
     */
    public function isCustom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCustom', array());

        return parent::isCustom();
    }

    /**
     * {@inheritDoc}
     */
    public function isDeprecated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDeprecated', array());

        return parent::isDeprecated();
    }

    /**
     * {@inheritDoc}
     */
    public function isPrivate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPrivate', array());

        return parent::isPrivate();
    }

    /**
     * {@inheritDoc}
     */
    public function isExtendedWarranty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isExtendedWarranty', array());

        return parent::isExtendedWarranty();
    }

    /**
     * {@inheritDoc}
     */
    public function getLicenseKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLicenseKey', array());

        return parent::getLicenseKey();
    }

    /**
     * {@inheritDoc}
     */
    public function getEditionNames()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEditionNames', array());

        return parent::getEditionNames();
    }

    /**
     * {@inheritDoc}
     */
    public function getEditionIds()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEditionIds', array());

        return parent::getEditionIds();
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', array());

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function isInstalled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isInstalled', array());

        return parent::isInstalled();
    }

    /**
     * {@inheritDoc}
     */
    public function getModuleInstalled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModuleInstalled', array());

        return parent::getModuleInstalled();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentityData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentityData', array());

        return parent::getIdentityData();
    }

    /**
     * {@inheritDoc}
     */
    public function getMarketplaceID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarketplaceID', array());

        return parent::getMarketplaceID();
    }

    /**
     * {@inheritDoc}
     */
    public function isTranslation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isTranslation', array());

        return parent::isTranslation();
    }

    /**
     * {@inheritDoc}
     */
    public function hasLicenseRestriction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasLicenseRestriction', array());

        return parent::hasLicenseRestriction();
    }

    /**
     * {@inheritDoc}
     */
    public function isSkinModule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSkinModule', array());

        return parent::isSkinModule();
    }

    /**
     * {@inheritDoc}
     */
    public function prepareBeforeUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prepareBeforeUpdate', array());

        return parent::prepareBeforeUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getInstalledURL()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstalledURL', array());

        return parent::getInstalledURL();
    }

    /**
     * {@inheritDoc}
     */
    public function getMarketplaceURL()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarketplaceURL', array());

        return parent::getMarketplaceURL();
    }

    /**
     * {@inheritDoc}
     */
    public function getModuleID()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getModuleID();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModuleID', array());

        return parent::getModuleID();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthor($author)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthor', array($author));

        return parent::setAuthor($author);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthor', array());

        return parent::getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthorEmail($authorEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthorEmail', array($authorEmail));

        return parent::setAuthorEmail($authorEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthorEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthorEmail', array());

        return parent::getAuthorEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($enabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', array($enabled));

        return parent::setEnabled($enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabled', array());

        return parent::getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setInstalled($installed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInstalled', array($installed));

        return parent::setInstalled($installed);
    }

    /**
     * {@inheritDoc}
     */
    public function getInstalled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstalled', array());

        return parent::getInstalled();
    }

    /**
     * {@inheritDoc}
     */
    public function setYamlLoaded($yamlLoaded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYamlLoaded', array($yamlLoaded));

        return parent::setYamlLoaded($yamlLoaded);
    }

    /**
     * {@inheritDoc}
     */
    public function getYamlLoaded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYamlLoaded', array());

        return parent::getYamlLoaded();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setRating($rating)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRating', array($rating));

        return parent::setRating($rating);
    }

    /**
     * {@inheritDoc}
     */
    public function getRating()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRating', array());

        return parent::getRating();
    }

    /**
     * {@inheritDoc}
     */
    public function setVotes($votes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVotes', array($votes));

        return parent::setVotes($votes);
    }

    /**
     * {@inheritDoc}
     */
    public function getVotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVotes', array());

        return parent::getVotes();
    }

    /**
     * {@inheritDoc}
     */
    public function setDownloads($downloads)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDownloads', array($downloads));

        return parent::setDownloads($downloads);
    }

    /**
     * {@inheritDoc}
     */
    public function getDownloads()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDownloads', array());

        return parent::getDownloads();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', array($price));

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', array());

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrency($currency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrency', array($currency));

        return parent::setCurrency($currency);
    }

    /**
     * {@inheritDoc}
     */
    public function setMajorVersion($majorVersion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMajorVersion', array($majorVersion));

        return parent::setMajorVersion($majorVersion);
    }

    /**
     * {@inheritDoc}
     */
    public function getMajorVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMajorVersion', array());

        return parent::getMajorVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setMinorVersion($minorVersion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMinorVersion', array($minorVersion));

        return parent::setMinorVersion($minorVersion);
    }

    /**
     * {@inheritDoc}
     */
    public function getMinorVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinorVersion', array());

        return parent::getMinorVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setBuild($build)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBuild', array($build));

        return parent::setBuild($build);
    }

    /**
     * {@inheritDoc}
     */
    public function getBuild()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBuild', array());

        return parent::getBuild();
    }

    /**
     * {@inheritDoc}
     */
    public function setMinorRequiredCoreVersion($minorRequiredCoreVersion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMinorRequiredCoreVersion', array($minorRequiredCoreVersion));

        return parent::setMinorRequiredCoreVersion($minorRequiredCoreVersion);
    }

    /**
     * {@inheritDoc}
     */
    public function getMinorRequiredCoreVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinorRequiredCoreVersion', array());

        return parent::getMinorRequiredCoreVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setRevisionDate($revisionDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRevisionDate', array($revisionDate));

        return parent::setRevisionDate($revisionDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getRevisionDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRevisionDate', array());

        return parent::getRevisionDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPackSize($packSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPackSize', array($packSize));

        return parent::setPackSize($packSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getPackSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPackSize', array());

        return parent::getPackSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setXcnPlan($xcnPlan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setXcnPlan', array($xcnPlan));

        return parent::setXcnPlan($xcnPlan);
    }

    /**
     * {@inheritDoc}
     */
    public function getXcnPlan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getXcnPlan', array());

        return parent::getXcnPlan();
    }

    /**
     * {@inheritDoc}
     */
    public function setModuleName($moduleName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModuleName', array($moduleName));

        return parent::setModuleName($moduleName);
    }

    /**
     * {@inheritDoc}
     */
    public function getModuleName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModuleName', array());

        return parent::getModuleName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthorName($authorName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthorName', array($authorName));

        return parent::setAuthorName($authorName);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthorName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthorName', array());

        return parent::getAuthorName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function setIconURL($iconURL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIconURL', array($iconURL));

        return parent::setIconURL($iconURL);
    }

    /**
     * {@inheritDoc}
     */
    public function getIconURL()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIconURL', array());

        return parent::getIconURL();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageURL($pageURL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageURL', array($pageURL));

        return parent::setPageURL($pageURL);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageURL()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageURL', array());

        return parent::getPageURL();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthorPageURL($authorPageURL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthorPageURL', array($authorPageURL));

        return parent::setAuthorPageURL($authorPageURL);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthorPageURL()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthorPageURL', array());

        return parent::getAuthorPageURL();
    }

    /**
     * {@inheritDoc}
     */
    public function setDependencies($dependencies)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDependencies', array($dependencies));

        return parent::setDependencies($dependencies);
    }

    /**
     * {@inheritDoc}
     */
    public function getDependencies()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDependencies', array());

        return parent::getDependencies();
    }

    /**
     * {@inheritDoc}
     */
    public function setTags($tags)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTags', array($tags));

        return parent::setTags($tags);
    }

    /**
     * {@inheritDoc}
     */
    public function getTags()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTags', array());

        return parent::getTags();
    }

    /**
     * {@inheritDoc}
     */
    public function setFromMarketplace($fromMarketplace)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFromMarketplace', array($fromMarketplace));

        return parent::setFromMarketplace($fromMarketplace);
    }

    /**
     * {@inheritDoc}
     */
    public function getFromMarketplace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFromMarketplace', array());

        return parent::getFromMarketplace();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsLanding($isLanding)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsLanding', array($isLanding));

        return parent::setIsLanding($isLanding);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsLanding()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsLanding', array());

        return parent::getIsLanding();
    }

    /**
     * {@inheritDoc}
     */
    public function setLandingPosition($landingPosition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLandingPosition', array($landingPosition));

        return parent::setLandingPosition($landingPosition);
    }

    /**
     * {@inheritDoc}
     */
    public function getLandingPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLandingPosition', array());

        return parent::getLandingPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsSystem($isSystem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsSystem', array($isSystem));

        return parent::setIsSystem($isSystem);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsSystem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsSystem', array());

        return parent::getIsSystem();
    }

    /**
     * {@inheritDoc}
     */
    public function setHasLicense($hasLicense)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHasLicense', array($hasLicense));

        return parent::setHasLicense($hasLicense);
    }

    /**
     * {@inheritDoc}
     */
    public function getHasLicense()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHasLicense', array());

        return parent::getHasLicense();
    }

    /**
     * {@inheritDoc}
     */
    public function setEditionState($editionState)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEditionState', array($editionState));

        return parent::setEditionState($editionState);
    }

    /**
     * {@inheritDoc}
     */
    public function getEditionState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEditionState', array());

        return parent::getEditionState();
    }

    /**
     * {@inheritDoc}
     */
    public function setEditions($editions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEditions', array($editions));

        return parent::setEditions($editions);
    }

    /**
     * {@inheritDoc}
     */
    public function getEditions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEditions', array());

        return parent::getEditions();
    }

    /**
     * {@inheritDoc}
     */
    public function setXbProductId($xbProductId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setXbProductId', array($xbProductId));

        return parent::setXbProductId($xbProductId);
    }

    /**
     * {@inheritDoc}
     */
    public function getXbProductId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getXbProductId', array());

        return parent::getXbProductId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsSkin($isSkin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsSkin', array($isSkin));

        return parent::setIsSkin($isSkin);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsSkin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsSkin', array());

        return parent::getIsSkin();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrivate($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrivate', array($value));

        return parent::setPrivate($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrivate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrivate', array());

        return parent::getPrivate();
    }

    /**
     * {@inheritDoc}
     */
    public function getWave()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWave', array());

        return parent::getWave();
    }

    /**
     * {@inheritDoc}
     */
    public function setWave($wave)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWave', array($wave));

        return parent::setWave($wave);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalesChannelPos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalesChannelPos', array());

        return parent::getSalesChannelPos();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalesChannelPos($salesChannelPos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalesChannelPos', array($salesChannelPos));

        return parent::setSalesChannelPos($salesChannelPos);
    }

    /**
     * {@inheritDoc}
     */
    public function getPurchaseStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPurchaseStatus', array());

        return parent::getPurchaseStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPurchaseStatus($purchaseStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPurchaseStatus', array($purchaseStatus));

        return parent::setPurchaseStatus($purchaseStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function _getPreviousState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '_getPreviousState', array());

        return parent::_getPreviousState();
    }

    /**
     * {@inheritDoc}
     */
    public function map(array $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'map', array($data));

        return parent::map($data);
    }

    /**
     * {@inheritDoc}
     */
    public function __unset($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__unset', array($name));

        return parent::__unset($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getRepository()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepository', array());

        return parent::getRepository();
    }

    /**
     * {@inheritDoc}
     */
    public function checkCache()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'checkCache', array());

        return parent::checkCache();
    }

    /**
     * {@inheritDoc}
     */
    public function detach()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'detach', array());

        return parent::detach();
    }

    /**
     * {@inheritDoc}
     */
    public function __call($method, array $args = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', array($method, $args));

        return parent::__call($method, $args);
    }

    /**
     * {@inheritDoc}
     */
    public function isPropertyExists($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPropertyExists', array($name));

        return parent::isPropertyExists($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setterProperty($property, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setterProperty', array($property, $value));

        return parent::setterProperty($property, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function getterProperty($property)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getterProperty', array($property));

        return parent::getterProperty($property);
    }

    /**
     * {@inheritDoc}
     */
    public function isPersistent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPersistent', array());

        return parent::isPersistent();
    }

    /**
     * {@inheritDoc}
     */
    public function isDetached()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDetached', array());

        return parent::isDetached();
    }

    /**
     * {@inheritDoc}
     */
    public function isManaged()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isManaged', array());

        return parent::isManaged();
    }

    /**
     * {@inheritDoc}
     */
    public function getUniqueIdentifierName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniqueIdentifierName', array());

        return parent::getUniqueIdentifierName();
    }

    /**
     * {@inheritDoc}
     */
    public function getUniqueIdentifier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniqueIdentifier', array());

        return parent::getUniqueIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityName', array());

        return parent::getEntityName();
    }

    /**
     * {@inheritDoc}
     */
    public function getFieldMetadata($property)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFieldMetadata', array($property));

        return parent::getFieldMetadata($property);
    }

    /**
     * {@inheritDoc}
     */
    public function update()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'update', array());

        return parent::update();
    }

    /**
     * {@inheritDoc}
     */
    public function create()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'create', array());

        return parent::create();
    }

    /**
     * {@inheritDoc}
     */
    public function delete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'delete', array());

        return parent::delete();
    }

    /**
     * {@inheritDoc}
     */
    public function processFiles($field, array $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'processFiles', array($field, $data));

        return parent::processFiles($field, $data);
    }

    /**
     * {@inheritDoc}
     */
    public function cloneEntity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'cloneEntity', array());

        return parent::cloneEntity();
    }

    /**
     * {@inheritDoc}
     */
    public function getFieldsDefinition($class = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFieldsDefinition', array($class));

        return parent::getFieldsDefinition($class);
    }

    /**
     * {@inheritDoc}
     */
    public function prepareEntityBeforeCommit($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prepareEntityBeforeCommit', array($type));

        return parent::prepareEntityBeforeCommit($type);
    }

    /**
     * {@inheritDoc}
     */
    public function isSerializable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSerializable', array());

        return parent::isSerializable();
    }

}
