<?php

namespace XLite\Model\Proxy\__CG__\XLite\Model\Payment;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BackendTransaction extends \XLite\Model\Payment\BackendTransaction implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * {@inheritDoc}
     * @param string $name
     */
    public function __get($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

        return parent::__get($name);
    }

    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', array($name, $value));

        return parent::__set($name, $value);
    }

    /**
     * {@inheritDoc}
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', array($name));

        return parent::__isset($name);

    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'date', 'status', 'value', 'type', 'payment_transaction', 'data', '_previous_state');
        }

        return array('__isInitialized__', 'id', 'date', 'status', 'value', 'type', 'payment_transaction', 'data', '_previous_state');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BackendTransaction $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getChargeValueModifier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChargeValueModifier', array());

        return parent::getChargeValueModifier();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentMethod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentMethod', array());

        return parent::getPaymentMethod();
    }

    /**
     * {@inheritDoc}
     */
    public function isSucceed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSucceed', array());

        return parent::isSucceed();
    }

    /**
     * {@inheritDoc}
     */
    public function isFailed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFailed', array());

        return parent::isFailed();
    }

    /**
     * {@inheritDoc}
     */
    public function isCompleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCompleted', array());

        return parent::isCompleted();
    }

    /**
     * {@inheritDoc}
     */
    public function isRefund()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isRefund', array());

        return parent::isRefund();
    }

    /**
     * {@inheritDoc}
     */
    public function isFullRefund()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFullRefund', array());

        return parent::isFullRefund();
    }

    /**
     * {@inheritDoc}
     */
    public function isCapture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCapture', array());

        return parent::isCapture();
    }

    /**
     * {@inheritDoc}
     */
    public function isVoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isVoid', array());

        return parent::isVoid();
    }

    /**
     * {@inheritDoc}
     */
    public function getReadableStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReadableStatus', array());

        return parent::getReadableStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function isOperationAllowed($operation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isOperationAllowed', array($operation));

        return parent::isOperationAllowed($operation);
    }

    /**
     * {@inheritDoc}
     */
    public function isInitial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isInitial', array());

        return parent::isInitial();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataCell($name, $value, $label = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataCell', array($name, $value, $label));

        return parent::setDataCell($name, $value, $label);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataCell($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataCell', array($name));

        return parent::getDataCell($name);
    }

    /**
     * {@inheritDoc}
     */
    public function registerTransactionInOrderHistory($suffix = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'registerTransactionInOrderHistory', array($suffix));

        return parent::registerTransactionInOrderHistory($suffix);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistoryEventDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistoryEventDescription', array());

        return parent::getHistoryEventDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getHistoryEventDescriptionData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistoryEventDescriptionData', array());

        return parent::getHistoryEventDescriptionData();
    }

    /**
     * {@inheritDoc}
     */
    public function getEventData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventData', array());

        return parent::getEventData();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setValue($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValue', array($value));

        return parent::setValue($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValue', array());

        return parent::getValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentTransaction(\XLite\Model\Payment\Transaction $paymentTransaction = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentTransaction', array($paymentTransaction));

        return parent::setPaymentTransaction($paymentTransaction);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentTransaction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentTransaction', array());

        return parent::getPaymentTransaction();
    }

    /**
     * {@inheritDoc}
     */
    public function addData(\XLite\Model\Payment\BackendTransactionData $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addData', array($data));

        return parent::addData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', array());

        return parent::getData();
    }

    /**
     * {@inheritDoc}
     */
    public function hasCustomAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasCustomAmount', array());

        return parent::hasCustomAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomAmount($amount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomAmount', array($amount));

        return parent::setCustomAmount($amount);
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomAmountRefundPart($amount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomAmountRefundPart', array($amount));

        return parent::setCustomAmountRefundPart($amount);
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomAmountRefundMulti($amount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomAmountRefundMulti', array($amount));

        return parent::setCustomAmountRefundMulti($amount);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxRefundAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxRefundAmount', array());

        return parent::getMaxRefundAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getParentValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentValue', array());

        return parent::getParentValue();
    }

    /**
     * {@inheritDoc}
     */
    public function _getPreviousState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '_getPreviousState', array());

        return parent::_getPreviousState();
    }

    /**
     * {@inheritDoc}
     */
    public function map(array $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'map', array($data));

        return parent::map($data);
    }

    /**
     * {@inheritDoc}
     */
    public function __unset($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__unset', array($name));

        return parent::__unset($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getRepository()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepository', array());

        return parent::getRepository();
    }

    /**
     * {@inheritDoc}
     */
    public function checkCache()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'checkCache', array());

        return parent::checkCache();
    }

    /**
     * {@inheritDoc}
     */
    public function detach()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'detach', array());

        return parent::detach();
    }

    /**
     * {@inheritDoc}
     */
    public function __call($method, array $args = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', array($method, $args));

        return parent::__call($method, $args);
    }

    /**
     * {@inheritDoc}
     */
    public function isPropertyExists($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPropertyExists', array($name));

        return parent::isPropertyExists($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setterProperty($property, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setterProperty', array($property, $value));

        return parent::setterProperty($property, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function getterProperty($property)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getterProperty', array($property));

        return parent::getterProperty($property);
    }

    /**
     * {@inheritDoc}
     */
    public function isPersistent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPersistent', array());

        return parent::isPersistent();
    }

    /**
     * {@inheritDoc}
     */
    public function isDetached()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDetached', array());

        return parent::isDetached();
    }

    /**
     * {@inheritDoc}
     */
    public function isManaged()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isManaged', array());

        return parent::isManaged();
    }

    /**
     * {@inheritDoc}
     */
    public function getUniqueIdentifierName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniqueIdentifierName', array());

        return parent::getUniqueIdentifierName();
    }

    /**
     * {@inheritDoc}
     */
    public function getUniqueIdentifier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniqueIdentifier', array());

        return parent::getUniqueIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityName', array());

        return parent::getEntityName();
    }

    /**
     * {@inheritDoc}
     */
    public function getFieldMetadata($property)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFieldMetadata', array($property));

        return parent::getFieldMetadata($property);
    }

    /**
     * {@inheritDoc}
     */
    public function update()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'update', array());

        return parent::update();
    }

    /**
     * {@inheritDoc}
     */
    public function create()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'create', array());

        return parent::create();
    }

    /**
     * {@inheritDoc}
     */
    public function delete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'delete', array());

        return parent::delete();
    }

    /**
     * {@inheritDoc}
     */
    public function processFiles($field, array $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'processFiles', array($field, $data));

        return parent::processFiles($field, $data);
    }

    /**
     * {@inheritDoc}
     */
    public function cloneEntity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'cloneEntity', array());

        return parent::cloneEntity();
    }

    /**
     * {@inheritDoc}
     */
    public function getFieldsDefinition($class = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFieldsDefinition', array($class));

        return parent::getFieldsDefinition($class);
    }

    /**
     * {@inheritDoc}
     */
    public function prepareEntityBeforeCommit($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prepareEntityBeforeCommit', array($type));

        return parent::prepareEntityBeforeCommit($type);
    }

    /**
     * {@inheritDoc}
     */
    public function isSerializable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSerializable', array());

        return parent::isSerializable();
    }

}
