<?php

namespace XLite\Model\Proxy\__CG__\XLite\Model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Profile extends \XLite\Model\Profile implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * {@inheritDoc}
     * @param string $name
     */
    public function __get($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

        return parent::__get($name);
    }

    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', array($name, $value));

        return parent::__set($name, $value);
    }

    /**
     * {@inheritDoc}
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', array($name));

        return parent::__isset($name);

    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'socialLoginProvider', 'socialLoginId', 'gaClientId', 'default_card_id', 'pending_zero_auth', 'pending_zero_auth_txn_id', 'pending_zero_auth_status', 'pending_zero_auth_interface', 'braintree_customer_id', 'braintreeCreditCards', 'braintreeCreditCardsHash', 'saveCardBoxChecked', 'conciergeUserId', 'mail_chimp_lists', 'mail_chimp_interests', 'mail_chimp_segments', 'conversations', 'profile_id', 'login', 'password', 'password_hint', 'password_hint_answer', 'passwordResetKey', 'passwordResetKeyDate', 'access_level', 'cms_profile_id', 'cms_name', 'added', 'first_login', 'last_login', 'status', 'statusComment', 'referer', 'order', 'event', 'language', 'last_shipping_id', 'last_payment_id', 'membership', 'pending_membership', 'addresses', 'roles', 'orders_count', 'anonymous', 'forceChangePassword', 'dateOfLoginAttempt', 'countOfLoginAttempts', 'searchFakeField', 'xcPendingExport', 'lastCheckoutEmail', '_previous_state');
        }

        return array('__isInitialized__', 'socialLoginProvider', 'socialLoginId', 'gaClientId', 'default_card_id', 'pending_zero_auth', 'pending_zero_auth_txn_id', 'pending_zero_auth_status', 'pending_zero_auth_interface', 'braintree_customer_id', 'braintreeCreditCards', 'braintreeCreditCardsHash', 'saveCardBoxChecked', 'conciergeUserId', 'mail_chimp_lists', 'mail_chimp_interests', 'mail_chimp_segments', 'conversations', 'profile_id', 'login', 'password', 'password_hint', 'password_hint_answer', 'passwordResetKey', 'passwordResetKeyDate', 'access_level', 'cms_profile_id', 'cms_name', 'added', 'first_login', 'last_login', 'status', 'statusComment', 'referer', 'order', 'event', 'language', 'last_shipping_id', 'last_payment_id', 'membership', 'pending_membership', 'addresses', 'roles', 'orders_count', 'anonymous', 'forceChangePassword', 'dateOfLoginAttempt', 'countOfLoginAttempts', 'searchFakeField', 'xcPendingExport', 'lastCheckoutEmail', '_previous_state');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Profile $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function isSocialProfile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSocialProfile', array());

        return parent::isSocialProfile();
    }

    /**
     * {@inheritDoc}
     */
    public function setSocialLoginProvider($socialLoginProvider)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSocialLoginProvider', array($socialLoginProvider));

        return parent::setSocialLoginProvider($socialLoginProvider);
    }

    /**
     * {@inheritDoc}
     */
    public function getSocialLoginProvider()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSocialLoginProvider', array());

        return parent::getSocialLoginProvider();
    }

    /**
     * {@inheritDoc}
     */
    public function setSocialLoginId($socialLoginId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSocialLoginId', array($socialLoginId));

        return parent::setSocialLoginId($socialLoginId);
    }

    /**
     * {@inheritDoc}
     */
    public function getSocialLoginId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSocialLoginId', array());

        return parent::getSocialLoginId();
    }

    /**
     * {@inheritDoc}
     */
    public function getGaClientId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGaClientId', array());

        return parent::getGaClientId();
    }

    /**
     * {@inheritDoc}
     */
    public function setGaClientId($gaClientId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGaClientId', array($gaClientId));

        return parent::setGaClientId($gaClientId);
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultCardId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultCardId', array());

        return parent::getDefaultCardId();
    }

    /**
     * {@inheritDoc}
     */
    public function getSavedCards()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSavedCards', array());

        return parent::getSavedCards();
    }

    /**
     * {@inheritDoc}
     */
    public function isCardIdValid($cardId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCardIdValid', array($cardId));

        return parent::isCardIdValid($cardId);
    }

    /**
     * {@inheritDoc}
     */
    public function allowRecharge($cardId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'allowRecharge', array($cardId));

        return parent::allowRecharge($cardId);
    }

    /**
     * {@inheritDoc}
     */
    public function denyRecharge($cardId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'denyRecharge', array($cardId));

        return parent::denyRecharge($cardId);
    }

    /**
     * {@inheritDoc}
     */
    public function setDefaultCardId($defaultCardId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDefaultCardId', array($defaultCardId));

        return parent::setDefaultCardId($defaultCardId);
    }

    /**
     * {@inheritDoc}
     */
    public function setPendingZeroAuth($pendingZeroAuth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPendingZeroAuth', array($pendingZeroAuth));

        return parent::setPendingZeroAuth($pendingZeroAuth);
    }

    /**
     * {@inheritDoc}
     */
    public function getPendingZeroAuth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPendingZeroAuth', array());

        return parent::getPendingZeroAuth();
    }

    /**
     * {@inheritDoc}
     */
    public function setPendingZeroAuthTxnId($pendingZeroAuthTxnId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPendingZeroAuthTxnId', array($pendingZeroAuthTxnId));

        return parent::setPendingZeroAuthTxnId($pendingZeroAuthTxnId);
    }

    /**
     * {@inheritDoc}
     */
    public function getPendingZeroAuthTxnId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPendingZeroAuthTxnId', array());

        return parent::getPendingZeroAuthTxnId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPendingZeroAuthStatus($pendingZeroAuthStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPendingZeroAuthStatus', array($pendingZeroAuthStatus));

        return parent::setPendingZeroAuthStatus($pendingZeroAuthStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getPendingZeroAuthStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPendingZeroAuthStatus', array());

        return parent::getPendingZeroAuthStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPendingZeroAuthInterface($pendingZeroAuthInterface)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPendingZeroAuthInterface', array($pendingZeroAuthInterface));

        return parent::setPendingZeroAuthInterface($pendingZeroAuthInterface);
    }

    /**
     * {@inheritDoc}
     */
    public function getPendingZeroAuthInterface()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPendingZeroAuthInterface', array());

        return parent::getPendingZeroAuthInterface();
    }

    /**
     * {@inheritDoc}
     */
    public function getBraintreeCreditCards()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBraintreeCreditCards', array());

        return parent::getBraintreeCreditCards();
    }

    /**
     * {@inheritDoc}
     */
    public function getBraintreeCreditCardsHash()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBraintreeCreditCardsHash', array());

        return parent::getBraintreeCreditCardsHash();
    }

    /**
     * {@inheritDoc}
     */
    public function setBraintreeCustomerId($braintreeCustomerId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBraintreeCustomerId', array($braintreeCustomerId));

        return parent::setBraintreeCustomerId($braintreeCustomerId);
    }

    /**
     * {@inheritDoc}
     */
    public function getBraintreeCustomerId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBraintreeCustomerId', array());

        return parent::getBraintreeCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    public function getSaveCardBoxChecked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSaveCardBoxChecked', array());

        return parent::getSaveCardBoxChecked();
    }

    /**
     * {@inheritDoc}
     */
    public function setSaveCardBoxChecked($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSaveCardBoxChecked', array($status));

        return parent::setSaveCardBoxChecked($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getConciergeUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConciergeUserId', array());

        return parent::getConciergeUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setConciergeUserId($conciergeUserId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConciergeUserId', array($conciergeUserId));

        return parent::setConciergeUserId($conciergeUserId);
    }

    /**
     * {@inheritDoc}
     */
    public function isSubscribedToMailChimpList(\XLite\Module\XC\MailChimp\Model\MailChimpList $list)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSubscribedToMailChimpList', array($list));

        return parent::isSubscribedToMailChimpList($list);
    }

    /**
     * {@inheritDoc}
     */
    public function isSubscribedToMailChimpSegment(\XLite\Module\XC\MailChimp\Model\MailChimpSegment $segment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSubscribedToMailChimpSegment', array($segment));

        return parent::isSubscribedToMailChimpSegment($segment);
    }

    /**
     * {@inheritDoc}
     */
    public function hasMailChimpSubscriptions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasMailChimpSubscriptions', array());

        return parent::hasMailChimpSubscriptions();
    }

    /**
     * {@inheritDoc}
     */
    public function getMailChimpListsIds()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailChimpListsIds', array());

        return parent::getMailChimpListsIds();
    }

    /**
     * {@inheritDoc}
     */
    public function checkSegmentsConditions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'checkSegmentsConditions', array());

        return parent::checkSegmentsConditions();
    }

    /**
     * {@inheritDoc}
     */
    public function checkGroupsConditions($listId, array $groupNameIds)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'checkGroupsConditions', array($listId, $groupNameIds));

        return parent::checkGroupsConditions($listId, $groupNameIds);
    }

    /**
     * {@inheritDoc}
     */
    public function doSubscribeToMailChimpLists($listsIds)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'doSubscribeToMailChimpLists', array($listsIds));

        return parent::doSubscribeToMailChimpLists($listsIds);
    }

    /**
     * {@inheritDoc}
     */
    public function doUnsubscribeFromMailChimpLists(array $listsIds)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'doUnsubscribeFromMailChimpLists', array($listsIds));

        return parent::doUnsubscribeFromMailChimpLists($listsIds);
    }

    /**
     * {@inheritDoc}
     */
    public function addMailChimpLists(\XLite\Module\XC\MailChimp\Model\MailChimpList $mailChimpLists)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMailChimpLists', array($mailChimpLists));

        return parent::addMailChimpLists($mailChimpLists);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailChimpLists()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailChimpLists', array());

        return parent::getMailChimpLists();
    }

    /**
     * {@inheritDoc}
     */
    public function addMailChimpSegments(\XLite\Module\XC\MailChimp\Model\MailChimpSegment $mailChimpSegments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMailChimpSegments', array($mailChimpSegments));

        return parent::addMailChimpSegments($mailChimpSegments);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailChimpSegments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailChimpSegments', array());

        return parent::getMailChimpSegments();
    }

    /**
     * {@inheritDoc}
     */
    public function addMailChimpInterests(\XLite\Module\XC\MailChimp\Model\MailChimpGroupName $mailChimpGroupName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMailChimpInterests', array($mailChimpGroupName));

        return parent::addMailChimpInterests($mailChimpGroupName);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailChimpInterests()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailChimpInterests', array());

        return parent::getMailChimpInterests();
    }

    /**
     * {@inheritDoc}
     */
    public function addConversation($conversation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addConversation', array($conversation));

        return parent::addConversation($conversation);
    }

    /**
     * {@inheritDoc}
     */
    public function getConversations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConversations', array());

        return parent::getConversations();
    }

    /**
     * {@inheritDoc}
     */
    public function countUnreadMessages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'countUnreadMessages', array());

        return parent::countUnreadMessages();
    }

    /**
     * {@inheritDoc}
     */
    public function countOwnUnreadMessages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'countOwnUnreadMessages', array());

        return parent::countOwnUnreadMessages();
    }

    /**
     * {@inheritDoc}
     */
    public function getNameForMessages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameForMessages', array());

        return parent::getNameForMessages();
    }

    /**
     * {@inheritDoc}
     */
    public function getVendorNameForMessages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVendorNameForMessages', array());

        return parent::getVendorNameForMessages();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferer($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferer', array($value));

        return parent::setReferer($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setMembership(\XLite\Model\Membership $membership = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMembership', array($membership));

        return parent::setMembership($membership);
    }

    /**
     * {@inheritDoc}
     */
    public function setPendingMembership(\XLite\Model\Membership $pendingMembership = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPendingMembership', array($pendingMembership));

        return parent::setPendingMembership($pendingMembership);
    }

    /**
     * {@inheritDoc}
     */
    public function getMembershipId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMembershipId', array());

        return parent::getMembershipId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPendingMembershipId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPendingMembershipId', array());

        return parent::getPendingMembershipId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName($useDefault = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array($useDefault));

        return parent::getName($useDefault);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingAddress', array());

        return parent::getBillingAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingAddress', array());

        return parent::getShippingAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingAddress($new)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingAddress', array($new));

        return parent::setBillingAddress($new);
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingAddress($new)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingAddress', array($new));

        return parent::setShippingAddress($new);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstAddress', array());

        return parent::getFirstAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function hasTaxExemption()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasTaxExemption', array());

        return parent::hasTaxExemption();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdersCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdersCount', array());

        return parent::getOrdersCount();
    }

    /**
     * {@inheritDoc}
     */
    public function isEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnabled', array());

        return parent::isEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function enable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'enable', array());

        return parent::enable();
    }

    /**
     * {@inheritDoc}
     */
    public function disable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'disable', array());

        return parent::disable();
    }

    /**
     * {@inheritDoc}
     */
    public function isAdmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAdmin', array());

        return parent::isAdmin();
    }

    /**
     * {@inheritDoc}
     */
    public function create()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'create', array());

        return parent::create();
    }

    /**
     * {@inheritDoc}
     */
    public function update($cloneMode = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'update', array($cloneMode));

        return parent::update($cloneMode);
    }

    /**
     * {@inheritDoc}
     */
    public function delete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'delete', array());

        return parent::delete();
    }

    /**
     * {@inheritDoc}
     */
    public function isSameAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSameAddress', array());

        return parent::isSameAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function isEqualAddress($strict = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEqualAddress', array($strict));

        return parent::isEqualAddress($strict);
    }

    /**
     * {@inheritDoc}
     */
    public function cloneEntity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'cloneEntity', array());

        return parent::cloneEntity();
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguage($flagCreate = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguage', array($flagCreate));

        return parent::getLanguage($flagCreate);
    }

    /**
     * {@inheritDoc}
     */
    public function setOrder(\XLite\Model\Order $order = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrder', array($order));

        return parent::setOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordAlgo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordAlgo', array());

        return parent::getPasswordAlgo();
    }

    /**
     * {@inheritDoc}
     */
    public function mergeWithProfile(\XLite\Model\Profile $profile, $flag = 3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'mergeWithProfile', array($profile, $flag));

        return parent::mergeWithProfile($profile, $flag);
    }

    /**
     * {@inheritDoc}
     */
    public function prepareBeforeCreate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prepareBeforeCreate', array());

        return parent::prepareBeforeCreate();
    }

    /**
     * {@inheritDoc}
     */
    public function prepareBeforeUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prepareBeforeUpdate', array());

        return parent::prepareBeforeUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function updateSearchFakeField()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateSearchFakeField', array());

        return parent::updateSearchFakeField();
    }

    /**
     * {@inheritDoc}
     */
    public function isPermissionAllowed($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPermissionAllowed', array($code));

        return parent::isPermissionAllowed($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfileId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfileId', array());

        return parent::getProfileId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogin($login)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogin', array($login));

        return parent::setLogin($login);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogin', array());

        return parent::getLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordHint($passwordHint)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordHint', array($passwordHint));

        return parent::setPasswordHint($passwordHint);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordHint()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordHint', array());

        return parent::getPasswordHint();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordHintAnswer($passwordHintAnswer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordHintAnswer', array($passwordHintAnswer));

        return parent::setPasswordHintAnswer($passwordHintAnswer);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordHintAnswer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordHintAnswer', array());

        return parent::getPasswordHintAnswer();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordResetKey($passwordResetKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordResetKey', array($passwordResetKey));

        return parent::setPasswordResetKey($passwordResetKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordResetKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordResetKey', array());

        return parent::getPasswordResetKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordResetKeyDate($passwordResetKeyDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordResetKeyDate', array($passwordResetKeyDate));

        return parent::setPasswordResetKeyDate($passwordResetKeyDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordResetKeyDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordResetKeyDate', array());

        return parent::getPasswordResetKeyDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccessLevel($accessLevel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccessLevel', array($accessLevel));

        return parent::setAccessLevel($accessLevel);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccessLevel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccessLevel', array());

        return parent::getAccessLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function setCmsProfileId($cmsProfileId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCmsProfileId', array($cmsProfileId));

        return parent::setCmsProfileId($cmsProfileId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCmsProfileId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCmsProfileId', array());

        return parent::getCmsProfileId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCmsName($cmsName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCmsName', array($cmsName));

        return parent::setCmsName($cmsName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCmsName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCmsName', array());

        return parent::getCmsName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdded($added)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdded', array($added));

        return parent::setAdded($added);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdded', array());

        return parent::getAdded();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstLogin($firstLogin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstLogin', array($firstLogin));

        return parent::setFirstLogin($firstLogin);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstLogin', array());

        return parent::getFirstLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastLogin($lastLogin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastLogin', array($lastLogin));

        return parent::setLastLogin($lastLogin);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastLogin', array());

        return parent::getLastLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatusComment($statusComment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatusComment', array($statusComment));

        return parent::setStatusComment($statusComment);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusComment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusComment', array());

        return parent::getStatusComment();
    }

    /**
     * {@inheritDoc}
     */
    public function getReferer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferer', array());

        return parent::getReferer();
    }

    /**
     * {@inheritDoc}
     */
    public function setLanguage($language)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanguage', array($language));

        return parent::setLanguage($language);
    }

    /**
     * {@inheritDoc}
     */
    public function setLastShippingId($lastShippingId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastShippingId', array($lastShippingId));

        return parent::setLastShippingId($lastShippingId);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastShippingId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastShippingId', array());

        return parent::getLastShippingId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastPaymentId($lastPaymentId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastPaymentId', array($lastPaymentId));

        return parent::setLastPaymentId($lastPaymentId);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastPaymentId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastPaymentId', array());

        return parent::getLastPaymentId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnonymous($anonymous)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnonymous', array($anonymous));

        return parent::setAnonymous($anonymous);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnonymous()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnonymous', array());

        return parent::getAnonymous();
    }

    /**
     * {@inheritDoc}
     */
    public function setForceChangePassword($forceChangePassword)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setForceChangePassword', array($forceChangePassword));

        return parent::setForceChangePassword($forceChangePassword);
    }

    /**
     * {@inheritDoc}
     */
    public function getForceChangePassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getForceChangePassword', array());

        return parent::getForceChangePassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateOfLoginAttempt($dateOfLoginAttempt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateOfLoginAttempt', array($dateOfLoginAttempt));

        return parent::setDateOfLoginAttempt($dateOfLoginAttempt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateOfLoginAttempt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateOfLoginAttempt', array());

        return parent::getDateOfLoginAttempt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountOfLoginAttempts($countOfLoginAttempts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountOfLoginAttempts', array($countOfLoginAttempts));

        return parent::setCountOfLoginAttempts($countOfLoginAttempts);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountOfLoginAttempts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountOfLoginAttempts', array());

        return parent::getCountOfLoginAttempts();
    }

    /**
     * {@inheritDoc}
     */
    public function setSearchFakeField($searchFakeField)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSearchFakeField', array($searchFakeField));

        return parent::setSearchFakeField($searchFakeField);
    }

    /**
     * {@inheritDoc}
     */
    public function getSearchFakeField()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSearchFakeField', array());

        return parent::getSearchFakeField();
    }

    /**
     * {@inheritDoc}
     */
    public function setXcPendingExport($xcPendingExport)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setXcPendingExport', array($xcPendingExport));

        return parent::setXcPendingExport($xcPendingExport);
    }

    /**
     * {@inheritDoc}
     */
    public function getXcPendingExport()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getXcPendingExport', array());

        return parent::getXcPendingExport();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrder', array());

        return parent::getOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function addEvent(\XLite\Model\OrderHistoryEvents $event)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEvent', array($event));

        return parent::addEvent($event);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvent', array());

        return parent::getEvent();
    }

    /**
     * {@inheritDoc}
     */
    public function getMembership()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMembership', array());

        return parent::getMembership();
    }

    /**
     * {@inheritDoc}
     */
    public function getPendingMembership()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPendingMembership', array());

        return parent::getPendingMembership();
    }

    /**
     * {@inheritDoc}
     */
    public function addAddresses(\XLite\Model\Address $addresses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAddresses', array($addresses));

        return parent::addAddresses($addresses);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddresses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddresses', array());

        return parent::getAddresses();
    }

    /**
     * {@inheritDoc}
     */
    public function addRoles(\XLite\Model\Role $roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRoles', array($roles));

        return parent::addRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function logoffSessions($exceptCurrent = true, $flush = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'logoffSessions', array($exceptCurrent, $flush));

        return parent::logoffSessions($exceptCurrent, $flush);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastCheckoutEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastCheckoutEmail', array());

        return parent::getLastCheckoutEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastCheckoutEmail($lastCheckoutEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastCheckoutEmail', array($lastCheckoutEmail));

        return parent::setLastCheckoutEmail($lastCheckoutEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function _getPreviousState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '_getPreviousState', array());

        return parent::_getPreviousState();
    }

    /**
     * {@inheritDoc}
     */
    public function map(array $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'map', array($data));

        return parent::map($data);
    }

    /**
     * {@inheritDoc}
     */
    public function __unset($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__unset', array($name));

        return parent::__unset($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getRepository()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepository', array());

        return parent::getRepository();
    }

    /**
     * {@inheritDoc}
     */
    public function checkCache()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'checkCache', array());

        return parent::checkCache();
    }

    /**
     * {@inheritDoc}
     */
    public function detach()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'detach', array());

        return parent::detach();
    }

    /**
     * {@inheritDoc}
     */
    public function __call($method, array $args = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', array($method, $args));

        return parent::__call($method, $args);
    }

    /**
     * {@inheritDoc}
     */
    public function isPropertyExists($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPropertyExists', array($name));

        return parent::isPropertyExists($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setterProperty($property, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setterProperty', array($property, $value));

        return parent::setterProperty($property, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function getterProperty($property)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getterProperty', array($property));

        return parent::getterProperty($property);
    }

    /**
     * {@inheritDoc}
     */
    public function isPersistent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPersistent', array());

        return parent::isPersistent();
    }

    /**
     * {@inheritDoc}
     */
    public function isDetached()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDetached', array());

        return parent::isDetached();
    }

    /**
     * {@inheritDoc}
     */
    public function isManaged()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isManaged', array());

        return parent::isManaged();
    }

    /**
     * {@inheritDoc}
     */
    public function getUniqueIdentifierName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniqueIdentifierName', array());

        return parent::getUniqueIdentifierName();
    }

    /**
     * {@inheritDoc}
     */
    public function getUniqueIdentifier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniqueIdentifier', array());

        return parent::getUniqueIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityName', array());

        return parent::getEntityName();
    }

    /**
     * {@inheritDoc}
     */
    public function getFieldMetadata($property)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFieldMetadata', array($property));

        return parent::getFieldMetadata($property);
    }

    /**
     * {@inheritDoc}
     */
    public function processFiles($field, array $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'processFiles', array($field, $data));

        return parent::processFiles($field, $data);
    }

    /**
     * {@inheritDoc}
     */
    public function getFieldsDefinition($class = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFieldsDefinition', array($class));

        return parent::getFieldsDefinition($class);
    }

    /**
     * {@inheritDoc}
     */
    public function prepareEntityBeforeCommit($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prepareEntityBeforeCommit', array($type));

        return parent::prepareEntityBeforeCommit($type);
    }

    /**
     * {@inheritDoc}
     */
    public function isSerializable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSerializable', array());

        return parent::isSerializable();
    }

}
